server:
  port: 9000

spring:
  application:
    name: finance-manager
  data-source:
    url: jdbc:mysql://localhost:3306/finance_manager
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true



